### ISSUE TITLE
Frontend language survey

### ISSUE THREAD

**Issue by cwgoes** [cryptiumlabs/juvix#218]
We should survey:
- Syntax convenience
- Proof developer experience
- Tactics
- etc.

in existing dependently-typed language frontends (Agda, Idris, Coq, etc.).

Subsequently, we should assemble a coherent synthesis of what package of features we want for the initial Juvix frontend.

cc @mariari @thealmarty

**Comment by mariari** [comment]
Another important idea to note is syntax extensibility. Ideally we'd pick a syntax such that users (including us) can extend the syntax to bring new features (such as type classes) without modifying the actual compiler.

I think this is a rather hard problem since we aren't a LISP, thus some surveying of non LISP macro systems are in due namely
- Coq
- Idris
- F*
- Elixir
- Haskell

should be looked at first.

**Comment by cwgoes** [comment]
Maybe we can pick one example (ref https://github.com/cryptiumlabs/juvix/issues/139) and write the example in several existing dependently-typed languages (& Juvix). That would be a useful point of comparison.

**Comment by cwgoes** [comment]
We should also survey the architecture of the Idris, Idris 2 & Agda compilers.

**Comment by cwgoes** [comment]
This may be a duplicate of https://github.com/cryptiumlabs/juvix/issues/3.

**Comment by thealmarty** [comment]
Closing. Consolidated to #3 .
