### ISSUE TITLE
Either use or remove HOAS in the typechecker

### ISSUE THREAD

**Issue by cwgoes** [cryptiumlabs/juvix#265]
Currently, we have both HOAS and the ability to refer to variables by context index ([which is *not* de-Bruijin indexed](https://gist.github.com/thealmarty/657a4484f104f801b50c64bd4924eae0)) in the typechecker, which is redundant. At the moment I am inclined to think that removing HOAS is probably best, since HOAS is a bit messy with the parameterisation and will be moreso when we need to return annotated IR.

**Comment by andy-morris** [comment]
Getting rid of HOAS will also make unification less fiddly, I think, so I'd prefer to go in that direction too.

**Comment by thealmarty** [comment]
Studying [Boxes go bananas](http://repository.upenn.edu/cgi/viewcontent.cgi?article=1031&context=cis_reports). Will report back.

**Comment by thealmarty** [comment]
> Studying [Boxes go bananas](https://www.seas.upenn.edu/~sweirich/papers/bgb-jfp.pdf). Will report back.

Didn't do the last part of the paper, but what I've implemented [so far](https://github.com/thealmarty/BoxesGoBananas) is a strict improvement of the current HOAS. Although it's still HOAS, it has the advantages of:
- [better syntax](https://github.com/thealmarty/BoxesGoBananas/blob/master/EgExpressions.hs) because `lam` and `app` are functions, the syntax can be easily customized and helper functions can be added more easily.
- better show instance for `lam` terms.
- de-bruijn indexes removed and thus HR form may be removed.

Let's see how #266 turns out and discuss how we want to go from there.

**Comment by cwgoes** [comment]
Do you think Boxes Go Bananas's version would still be nice if the result of typechecking / evaluation was in a monad (we'll want that for error handling & logging)?

One option could be to have the typechecker in non-HOAS (monadic), but have a HOAS interface (non-monadic, quoted to non-HOAS) available for convenience in test writing.

**Comment by thealmarty** [comment]
> Do you think Boxes Go Bananas's version would still be nice if the result of typechecking / evaluation was in a monad (we'll want that for error handling & logging)?

Shouldn't be a problem.

**Comment by cwgoes** [comment]
@andy-morris Presumably it makes sense to do this along with the updates to first-class usages.

I think the easiest move is to move away from HOAS, at least for the core logic (maybe we could add a HOAS wrapper later, but we don't need one immediately).

**Comment by andy-morris** [comment]
(done as part of #356)
