### ISSUE TITLE
Documentation on the oracle of interaction nets

### ISSUE THREAD

**Issue by Heimdell** [cryptiumlabs/juvix#84]
Hello!

It would be nice to read documentation on your implementation of oracle algorithm, if you have any.

**Comment by cwgoes** [comment]
Juvix does not use the oracle at the moment, and we don't plan to due to the runtime overhead.

EAL-typable lambda terms can be translated into interaction nets which can be reduced using Lamping's abstract algorithm only (with integer labels on fans), and Juvix has the ability to infer EAL typeability. Non-EAL-typeable terms or terms which are EAL-typeable but for which the overhead of graph rewriting is too high (e.g. small tail-recursive numerical functions) can be compiled by a separate compiler path into custom rewrite rules which respect the laws of interaction nets.

The language reference documents parts of this but is not yet complete (nor is the code).
If you are interested in reading more I also suggest these two papers:
- [Light logics and Optimal Reduction: Completeness & Complexity](https://www.sciencedirect.com/science/article/pii/S0890540110001604)
- [A feasible algorithm for typing in Elementary Affine Logic](https://arxiv.org/abs/cs/0412028)

**Comment by cwgoes** [comment]
Rolling this into https://github.com/cryptiumlabs/juvix/issues/90.
